name: Validate PR

on:
  pull_request:
    branches: [main, test4]
    types: [opened, edited]

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Run install
        run: pnpm install --no-frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test

      - name: Commits Signature validation
        run: |
          COMMITS=$(gh pr view ${{ github.event.pull_request.number }} --json commits -q '.commits[].oid')
          for SHA in $COMMITS; do
            AUTHOR_EMAIL=$(git show -s --format='%ae' $SHA)
            SIGNATURE_STATUS=$(git verify-commit $SHA 2>&1 || echo "unsigned")
            echo "Checking $SHA from $AUTHOR_EMAIL"

            if [[ "$AUTHOR_EMAIL" == *@zohocorp.com ]]; then
              if [[ "$SIGNATURE_STATUS" == *"gpg: Signature made"* ]]; then
                echo "Commit $SHA by $AUTHOR_EMAIL is signed"
              else
                echo "Commit $SHA by $AUTHOR_EMAIL is not signed"
                exit 1
              fi
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR author username
        id: pr
        uses: actions/github-script@v7
        with:
          script: return context.payload.pull_request.user.login
          result-encoding: string

      - name: Check if user signed CLA
        run: |
          PR_USER="${{ steps.pr.outputs.result }}"
          echo "PR by $PR_USER"

          if grep -Fxq "$PR_USER" .contributor-list.txt; then
            echo "✅ $PR_USER has signed the CLA"
          else
            echo "::error ::$PR_USER has not signed the CLA. Please email the signed CLA to support@zohocatalyst.com"
            exit 1
          fi
