name: Release

on:
  push:
    branches:
      - test4

jobs:
  release:
    name: Publish to npm
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Run install
        run: pnpm install --no-frozen-lockfile

      - name: Create tag
        run: node scripts/create-tag.js

      - name: Release updated packages to npm
        run: node scripts/release-packages.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Get version from package.json
        id: version
        run: |
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      
      - name: Extract latest changelog entry
        id: changelog
        run: |
          changelog=$(awk '/^## \[.*\]/ { if (found) exit; found=1 } found { print }' CHANGELOG.md)
          echo "body<<EOF" >> "$GITHUB_OUTPUT"
          echo "$changelog" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body: |
            This release was automatically generated by the release workflow.
            It includes all changes since the last release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
