name: Verify Commit Signatures

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-signed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get PR commits
        run: |
          COMMITS=$(gh pr view ${{ github.event.pull_request.number }} --json commits -q '.commits[].oid')
          for SHA in $COMMITS; do
            AUTHOR_EMAIL=$(git show -s --format='%ae' $SHA)
            SIGNATURE_STATUS=$(git verify-commit $SHA 2>&1 || echo "unsigned")
            echo "Checking $SHA from $AUTHOR_EMAIL"

            if [[ "$AUTHOR_EMAIL" == *@zohocorp.com ]]; then
              if [[ "$SIGNATURE_STATUS" == *"gpg: Signature made"* ]]; then
                echo "✅ Commit $SHA by $AUTHOR_EMAIL is signed"
              else
                echo "❌ Commit $SHA by $AUTHOR_EMAIL is not signed"
                exit 1
              fi
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
